namespace DynamicDataVNext;

/// <summary>
/// Defines the types of multi-item change sets that can be represented within this library.
/// </summary>
/// <remarks>
/// This allows consumers to optimize how they process certain common actions, namely clear and reset actions, by applying the appropriate action without having to iterate over every individual change.
/// </remarks>
public enum ChangeSetType
{
    /// <summary>
    /// Describes a change set that contains no changes, and can be ignored.
    /// </summary>
    /// <remarks>
    /// Generally, this type of change set should never be generated by the library, but exists to allow for <see langword="default"/> changesets to be valid.
    /// </remarks>
    Empty,
    /// <summary>
    /// Describes a change set that contains an assortment of individual changes, which cannot be generalized.
    /// </summary>
    Update,
    /// <summary>
    /// Describes an operation to remove all items from a collection. The change set will contain a <see cref="ChangeCategory.Removal"/> for every item in the source collection.
    /// </summary>
    Clear,
    /// <summary>
    /// Describes an operation that replaces the items in a collection (if any) with a new set of items. The change set will contain a <see cref="ChangeCategory.Removal"/> for every item in the source collection (if any), followed by an <see cref="ChangeCategory.Addition"/> for each of the new items.
    /// </summary>
    Reset
}
