namespace DynamicDataVNext;

/// <summary>
/// Defines a shared set of change actions that are supported by all types of collections. 
/// </summary>
/// <remarks>
/// This exists exclusively for the sake of identifying when a sequence of changes can be categorized as a <see cref="ChangeSetType.Reset"/> operation.
/// </remarks>
public enum ChangeCategory
{
    /// <summary>
    /// A placeholder for the lack of a change being performed.
    /// </summary>
    /// <remarks>
    /// This type of change should never be generated by the library, but exists to allow for <see langword="default"/> changes to be valid.
    /// </remarks>
    None,
    /// <summary>
    /// Describes the addition of an item to a collection.
    /// </summary>
    Addition,
    /// <summary>
    /// Describes the removal of an item from a collection.
    /// </summary>
    Removal,
    /// <summary>
    /// Describes all other types of single-item changes, within a collection.
    /// </summary>
    Other
}
